# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='DanLop', max_length=50, verbose_name='username'),
        ),
    ]
